version: "3.8"
services:
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa-server
    ports:
      - "8181:8181"
    volumes:
      - ./opa-config:/policies
    networks:
      - poc
    command: ["run", "--server", "/policies"]

networks:
  poc:
    driver: bridge
